import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import "@rainbow-me/rainbowkit/styles.css";
import RainbowKitContext from "@/components/RainbowKit";
import { Toaster } from "react-hot-toast";
import IMAGEKIT from "./home/images";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Antigravity | Join The Revolution!",
  description: "Generated by create next app",
  icons: { icon: "/icon.png" },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="hidden md:block">
          <Toaster />
          <RainbowKitContext>{children}</RainbowKitContext>
        </div>
        <div className="block md:hidden">
          <div
            className={`max-h-screen h-screen w-screen bg-[url('${IMAGEKIT.HERO_LANDING}')]`}
          >
            <h1>Join Us On Desktop! </h1>
          </div>
        </div>
      </body>
    </html>
  );
}
