import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import "@rainbow-me/rainbowkit/styles.css";
import RainbowKitContext from "@/components/RainbowKit";
import { Toaster } from "react-hot-toast";
import MobileView from "./home/MobileView";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Antigravity | Join The Revolution!",
  description: "Generated by create next app",
  icons: { icon: "/icon.png" },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="hidden md:block">
          <Toaster />
          <RainbowKitContext>{children}</RainbowKitContext>
        </div>
        <div className="md:hidden block">
          <MobileView />
        </div>
      </body>
    </html>
  );
}
